### ISSUE TITLE
Commands on Stage 2 doesn't work for me

### ISSUE THREAD

**Issue by ghost** [annacrombie/muon#45] opened 2024-06-05 12:16 UTC
I'm on Windows 7 (without MSYS2) so I'm using a standalone MinGW-w64 distro with Windows Command Prompt. It seems the developer doesn't have this setup in mind. I don't know if his support for MSVC is any better, too.

Please note that I have managed to have muon bootstrapped successfully (see: #37).

I have to change `build/muon` into `build\muon.exe` for the command to be able to run.

`build\muon.exe setup build` worked. But `build\muon.exe -C build samu` failed. I inserted `-v` and this is the error message:

```
C:\Work\muon>build\muon.exe -v -C build_muon samu
[1/129] compiling c subprojects/tinyjson/libtiny-json.a.p/tiny-json.c.o
dbg executing : '"/bin/sh" -c gcc -std=c99 -g -O0 -Wpedantic -Wextra -Wall -I subprojects/tinyjson -I ../subprojects/tinyjson -MD -MQ subprojects/tinyjson/libtiny-json.a.p/tiny-json.c.o -MF subprojects/tinyjson/libtiny-json.a.p/tiny-json.c.o.d -o subprojects/tinyjson/libtiny-json.a.p/tiny-json.c.o -c ../subprojects/tinyjson/tiny-json.c'
err CreateProcess() failed: The system cannot find the file specified.
samu: failed to start job: failed to create process
samu: job failed to start
samu: subcommand failed
```

Why muon is trying to invoke sh on a pure Windows environment?

**Comment by vtorri** [comment] 2024-06-05 17:05
i can build muon with the Visual Studio command prompt. I've not tried with gcc on Windows in cmd. That's a bug.

**Comment by iahunq2** [comment] 2024-06-05 18:48
> i can build muon with the Visual Studio command prompt. I've not tried with gcc on Windows in cmd. That's a bug.

Do you use the same command as Stage 2? Because if using a standalone ninja I can also build muon. The bug is of samu.

**Comment by vtorri** [comment] 2024-06-05 18:50
i've not tried samu yet, too young imho. I have other stuff to do on Windows, like the vs backend. 

And i would also like to add cross compilation

**Comment by vtorri** [comment] 2024-06-08 12:40
`_WIN32` is not defined by cygwin compilers

**Comment by vtorri** [comment] 2024-06-08 12:42
btw, i wonder why you decided that we are on windows (machines.c line 354) if we are also in cygwin environment

**Comment by iahunq2** [comment] 2024-06-09 00:17
> @vtorri is that wrong? Should it just be `build_machine.sys == machine_system_windows`?

I modified machines.c so it's now only `build_machine.sys == machine_system_windows`. I can confirm that it's still calling `/bin/sh`.

**Comment by iahunq2** [comment] 2024-06-09 00:32
It seems you are relying entirely on the result of `uname` which simply doesn't exist on Windows. And as I and @vtorri have noted in #41, the result of `uname` can't be relied on MSYS2 because each MSYS2 environment will report a different value for `uname`. For example, the UCRT64 environment will have `uname -s` starts with `MINGW64_NT`. Your current code is only valid for the MSYS environment of MSYS2 which has `uname -s` starts with `MSYS_NT`. I also described what you could use instead of `uname` on MSYS2.

**Comment by vtorri** [comment] 2024-06-09 07:39
see https://github.com/annacrombie/muon/issues/41#issuecomment-2156362217

**Comment by iahung2** [comment] 2024-06-09 22:51
@annacrombie Please close this issue. The problem suddenly gone when I built against a newly cloned muon repository. The previous one I'm working with is from my own fork (not this repository). I don't know why it's this way because I have not modified anything in my fork. Maybe that github account is corrupted (I deleted it anyway).

**Closed as completed** 2024-07-22 15:35 UTC
